# -*- coding: utf-8 -*-
"""FACTORIAL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13FVfIdbMkswdIT-DqEyfCGC7xf1mQM8E

FACTORIAL
"""

x=5
fact=1
for i in range(1,x+1):
    fact=fact*i
print(fact)