# -*- coding: utf-8 -*-
"""FIBONACCI SERIES

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rhkjZX1gbZAn8ZHMKzU3hy3Lj-4dNjQq

FIBONACCI SERIES
"""

n=10
a=0
b=1

for i in range(n):
  print(a,end=" ")
  next = a+b
  a=b
  b=next