# -*- coding: utf-8 -*-
"""LEC-4_25BCON0748

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vt0SNdF-8-kemPTjlsz3IXCAPcS6PE-3

THIS IS MY FIRST PROGRAM
"""

print(5)

"""STRUCT DICT

"""

class Student:
    def __init__(self):
        self.name = ""
        self.roll = 0
        self.marks = 0.0


s1 = Student()

s1.name = "Rahul"
s1.roll = 101
s1.marks = 87.5

print("Name:", s1.name)
print("Roll:", s1.roll)
print("Marks:", s1.marks)

"""In C adding a new field to a struct requires a changing the struct definition. What happens in python when you add a new key to dictionary while the program is running- and what is that both useful and risky ?

Why is this useful?
Flexible: You can add or remove information whenever needed.
No need to redefine the dictionary.
Useful when data is dynamic or unpredictable, such as JSON/API data.
Why is it risky?
A key can be misspelled, creating an unintended new key:
Now "marrks" and "marks" are two different keys.

The program may expect a key that doesn't exist, causing errors such as KeyError.
Unlike a C struct, Python dictionaries don't enforce a fixed structure.

In short: Python dictionaries are more flexible than C structs, but that flexibility can lead to unexpected or inconsistent data.
"""